SOLIDApp/Controllers/GraspController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SOLIDApp.Controllers
{
    public class GraspController : Controller
    {
        // GET: Grasp
        public ActionResult Index()
        {
            return View();
        }
    }
}

SOLIDApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SOLIDApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Demo presenting Object Oriented Design principles and popular Design Patterns.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact Details:";

            return View();
        }
        public ActionResult OOD()
        {
            return View();
        }
    }
}

SOLIDApp/Controllers/OODController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SOLIDApp.Controllers
{
    public class OODController : Controller
    {
        // GET: OOD
        public ActionResult Index()
        {
            return View();
        }
    }
}

SOLIDApp/Controllers/PatternsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SOLIDApp.Controllers {

    public class PatternsController : Controller {

        // GET: Patterns
        public ActionResult Index() {
            return View();
        }
    }
}

SOLIDApp/Controllers/SolidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SOLIDApp.Controllers {

    public class SolidController : Controller {

        // GET: Solid
        public ActionResult Index() {
            return View();
        }
    }
}

SOLIDApp/Views/Grasp/Index.cshtml
@{
    ViewBag.Title = "GRASP";
}

<div class="jumbotron">
    <h1>GRASP</h1>
    <p class="lead">
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2></h2>
        <p>
        </p>
    </div>
    <div class="col-md-4">
        <h2></h2>
        <p>
        </p>
    </div>
    <div class="col-md-4">
        <h2></h2>
        <p>
        </p>
    </div>
</div>

SOLIDApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

SOLIDApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Thomas Rogozinski<br />
    <abbr title="Phone">P:</abbr>
    .... ... ...
</address>

<address>
    <strong>Company Email:</strong>   <a href="mailto:Company@example.com">thomas@xxx.com</a><br />
    <strong>Private Email:</strong> <a href="mailto:Private@example.com">thomas@xxx.com</a>
</address>

SOLIDApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>SOLID Web App</h1>
    <p class="lead">
        Demo of real-world code implementing Object Oriented Design principles, Gang of Four Design Patterns and concepts of SOLID and GRASP
        which helps to avoid a bad software design and create one which is flexible, modular, easy to modify, reuse, extend, scale, port, test and maintain.
        SOLID Web App presents sample solutions for particular design problems and their implementation in C#.
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Object Oriented Design</h2>
        <p>
            follows 4 major principles built into every object-oriented language: Encapsulation, Abstraction, Inheritance, Polymorphism.
        </p>
    </div>
    <div class="col-md-4">
        <h2>Design Patterns</h2>
        <p>
            are solutions to software design problems repeatable found in application development. The most popular 23 Gang of Four patterns are grouped in three categories: Creational, Structural and Behavioural.
            Abstract Factory, Builder, Factory Method, Prototype, Singleton, Adapter, Bridge, Composite, Decorator, Facade, Flyweight, Proxy, Chain of Responsibility, Command, Interpreter, Iterator, Mediator, Memento, Observer, State, Strategy, Template Method, Visitor.
        </p>
    </div>
    <div class="col-md-4">
        <h2>SOLID</h2>
        <p>
            architecture provides five basic principles which are necessary to follow to build sound systems: <b>S</b>ingle Responsibility, <b>O</b>pen Closed, <b>L</b>iskov Substitution, <b>I</b>nterface Segregation, <b>D</b>ependency Inversion.
        </p>
    </div>
    <div class="col-md-4">
        <h2>GRASP</h2>
        <p>
            <b>G</b>eneral <b>R</b>esponsibility <b>A</b>ssignment Software <b>P</b>atterns consist of number of patterns regarded as basic in almost every software project: Controller, Creator, Indirection, Information Expert, High Cohesion, Low Coupling, Polymorphism, Protected Variations, Pure Fabrications.
        </p>
    </div>
</div>

SOLIDApp/Views/OOD/Index.cshtml
@{
    ViewBag.Title = "OOD";
}

<header>
    <div class="content-wrapper">
        <div class="float-left">
            <h1>@ViewBag.Title</h1>
        </div>
    </div>
</header>
<div id="body">
    <section class="featured">
        <div class="content-wrapper">
            <p>
            </p>
        </div>
    </section>
    <section class="content-wrapper main-content clear-fix">
        <h3></h3>
        <ol class="round">
            <li class="one">
                <h5></h5>
            </li>
            <li class="two">
                <h5></h5>
            </li>
            <li class="three">
                <h5></h5>
            </li>
            <li class="four">
                <h5></h5>
            </li>
        </ol>
    </section>
</div>

SOLIDApp/Views/Patterns/Index.cshtml
@{
    ViewBag.Title = "Patterns";
}

<div class="jumbotron">
    <h1>Design Patterns</h1>
    <p class="lead">
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2></h2>
        <p>
        </p>
    </div>
    <div class="col-md-4">
        <h2></h2>
        <p>
        </p>
    </div>
    <div class="col-md-4">
        <h2></h2>
        <p>
        </p>
    </div>
</div>

SOLIDApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("OOD", "Index", "OOD", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Design Patterns", "Index", "Patterns", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("SOLID", "Index", "Solid", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("GRASP", "Index", "Grasp", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
               </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SOLIDApp/Views/Solid/Index.cshtml
@{
    ViewBag.Title = "SOLID";
}

<div class="jumbotron">
    <h1>SOLID Architecture</h1>
    <p class="lead">
        Software design principles represent a set of guidelines that helps us to avoid having a bad design.
        The design principles are associated to Robert Martin who gathered them in "Agile Software Development: Principles, Patterns, and Practices".
        According to Robert Martin there are 3 important characteristics of a bad design that should be avoided:

        Rigidity - It is hard to change because every change affects too many other parts of the system.
        Fragility - When you make a change, unexpected parts of the system break.
        Immobility - It is hard to reuse in another application because it cannot be disentangled from the current application.
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Single responsibility principle</h2>
        <p>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Open/closed principle</h2>
        <p>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Liskov substitution principle</h2>
        <p>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Interface segregation principle</h2>
        <p>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Dependency inversion principle</h2>
        <p>
        </p>
    </div>
</div>